Use "inf" instead of "infinity" for function composition intervals
openwebwork/webwork-open-problem-library pull request #1136
Opened 2024-03-10 17:17 UTC by d-torrance

This way, these problems will accept input from the MathQuill editor.

2024-03-10 18:26 UTC, dpvc commented
I think these should all be converted to MathObjects, where both `inf` and `infinity` mean the same thing, and you will get better error messages for wrong answers.  Just my 2 cents.

2024-03-12 12:08 UTC, d-torrance commented
Sounds good!  I've adapted each of the problems to use MathObjects.

2024-03-12 16:24 UTC, dlglin commented
There are a number of other things that could (should?) be done to bring these problems up to modern standards:

- `TEXT(beginproblem());` can be removed.  It no longer does anything.
- `TEXT(EV2(<<EOT));`/`EOT` should be replaced with `BEGIN_TEXT`/`END_TEXT`.  Better yet the problem text should be converted to PGML.
- The current answer blank structure telegraphs the answers.  If it asks for a single interval then the answer is always (-inf,inf).  If it asks for the non-permissible values then it only accepts one number.  I'd suggest using the interval context for all domains and replacing the instructions with `helpLink('interval')`.

Let me know if you want me to code any of these changes.

2024-03-12 18:19 UTC, d-torrance commented
I've pushed a few new commits addressing the suggestions, except I didn't convert them to PGML since that would require a bit more work.

2024-03-12 21:49 UTC, dlglin requested changes
The `reduce` calls will combine some of the constants and make the correct answers look nicer.  Also there is one answer that you missed converting to an interval.

2024-03-12 21:49 UTC, dlglin commented on OpenProblemLibrary/Rochester/setAlgebra17FunComposition/srw2_8_1.pg
> +$ans11 = Compute(-$b);
```suggestion
$ans1 = Compute("x**2-($a-1)*x+$b")->reduce();
$ans2 = Compute("(-inf, inf)");
$ans4 = Compute("x**2-($a+1)*x-$b")->reduce();
$ans5 = Compute("(-inf, inf)");
$ans7 = Compute("(x**2-$a*x)*(x+$b)")->reduce();
$ans8 = Compute("(-inf, inf)");
$ans10 = Compute("(x**2-$a*x)/(x+$b)")->reduce();
$ans11 = Compute("(-inf,-$b)U(-$b,inf)");
```

2024-03-12 21:49 UTC, dlglin commented on OpenProblemLibrary/Rochester/setAlgebra17FunComposition/sw4_7_31.pg
> +$ans11 = Compute("(-inf, inf)");
```suggestion
$ans1 = Compute("(x + $b)**2+$a")->reduce();
$ans2 = Compute("(-inf, inf)");
$ans4 = Compute("x**2 + $a+$b")->reduce();
$ans5 = Compute("(-inf, inf)");
$ans7 = Compute("(x**2 + $a)**2+$a")->reduce();
$ans8 = Compute("(-inf, inf)");
$ans10 = Compute("x + 2*$b")->reduce();
$ans11 = Compute("(-inf, inf)");
```

2024-03-12 21:50 UTC, dlglin commented
Also, thanks for doing the extra work on the problems.

2024-03-13 16:26 UTC, dlglin approved these changes

2024-03-27 10:22 UTC, pstaabp approved these changes
Looks good.  I would agree that this should be converted to PGML, but is still a nice improvement.

2024-03-27 10:22 UTC, merged