Added particle dynamics problems to Douglas College
openwebwork/webwork-open-problem-library pull request #847
Opened 2021-07-06 18:23 UTC by GraemeDockrill

2021-07-06 19:05 UTC, drdrew42 requested changes
Please revert changes made to Contrib/CUNY/CityTech/CollegeAlgebra_Trig/ReducingRationalExpressions/monoDenom-Scaff.pg

You may save a new version of this file within your institution's directory.

2021-07-06 20:07 UTC, GraemeDockrill commented
It should be fixed now. I don't know why that file was updated.

2021-07-07 00:07 UTC, drdrew42 approved these changes

2021-07-07 00:08 UTC, drdrew42 commented
No worries, thanks for making the change 👍

2021-07-07 00:08 UTC, merged